// <auto-generated />
using System;
using HBP.Domain.Enums;
using HBP.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HBP.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HbpDbContext))]
    [Migration("20260716161344_AddLoginLockout")]
    partial class AddLoginLockout
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "booking_request_status", new[] { "RECEIVED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "email_status", new[] { "PENDING", "SENT", "RETRYING", "FAILED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "language_code_enum", new[] { "vi", "ja" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "price_display_mode", new[] { "SHOW_PRICE", "CONTACT" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HBP.Domain.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<int>("FailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_count");

                    b.Property<DateTime?>("FirstFailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_failed_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_admin_users_email_lower");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("uq_admin_users_username_lower");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("HBP.Domain.Entities.Amenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_visible");

                    b.Property<string>("NameJa")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name_ja");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name_vi");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("amenities", null, t =>
                        {
                            t.HasCheckConstraint("ck_amenities_display_order", "display_order >= 0");
                        });
                });

            modelBuilder.Entity("HBP.Domain.Entities.BookingRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Adults")
                        .HasColumnType("integer")
                        .HasColumnName("adults");

                    b.Property<DateOnly?>("CheckInDate")
                        .HasColumnType("date")
                        .HasColumnName("check_in_date");

                    b.Property<DateOnly?>("CheckOutDate")
                        .HasColumnType("date")
                        .HasColumnName("check_out_date");

                    b.Property<int?>("Children")
                        .HasColumnType("integer")
                        .HasColumnName("children");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CustomerMessage")
                        .HasColumnType("text")
                        .HasColumnName("customer_message");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<LanguageCode>("LanguageCode")
                        .HasColumnType("language_code_enum")
                        .HasColumnName("language_code");

                    b.Property<int?>("NumberOfRooms")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_rooms");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reference_code");

                    b.Property<Guid?>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.Property<BookingRequestStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("booking_request_status")
                        .HasDefaultValue(BookingRequestStatus.RECEIVED)
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_booking_requests_created_at");

                    b.HasIndex("ReferenceCode")
                        .IsUnique()
                        .HasDatabaseName("uq_booking_requests_reference_code");

                    b.HasIndex("RoomTypeId")
                        .HasDatabaseName("idx_booking_requests_room_type_id");

                    b.ToTable("booking_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_booking_requests_adults", "adults >= 1");

                            t.HasCheckConstraint("ck_booking_requests_children", "children IS NULL OR children >= 0");

                            t.HasCheckConstraint("ck_booking_requests_number_of_rooms", "number_of_rooms IS NULL OR number_of_rooms >= 1");
                        });
                });

            modelBuilder.Entity("HBP.Domain.Entities.ContactRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<LanguageCode>("LanguageCode")
                        .HasColumnType("language_code_enum")
                        .HasColumnName("language_code");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reference_code");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_contact_requests_created_at");

                    b.HasIndex("ReferenceCode")
                        .IsUnique()
                        .HasDatabaseName("uq_contact_requests_reference_code");

                    b.ToTable("contact_requests", (string)null);
                });

            modelBuilder.Entity("HBP.Domain.Entities.EmailDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EmailType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email_type");

                    b.Property<LanguageCode>("LanguageCode")
                        .HasColumnType("language_code_enum")
                        .HasColumnName("language_code");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("recipient");

                    b.Property<Guid>("RelatedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("related_entity_type");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<EmailStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("email_status")
                        .HasDefaultValue(EmailStatus.PENDING)
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("NextRetryAt")
                        .HasDatabaseName("idx_email_deliveries_next_retry")
                        .HasFilter("status = 'RETRYING'");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_email_deliveries_status");

                    b.HasIndex("RelatedEntityType", "RelatedEntityId")
                        .HasDatabaseName("idx_email_deliveries_related_entity");

                    b.ToTable("email_deliveries", null, t =>
                        {
                            t.HasCheckConstraint("ck_email_deliveries_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_email_deliveries_related_entity_type", "related_entity_type IN ('BookingRequest', 'ContactRequest')");
                        });
                });

            modelBuilder.Entity("HBP.Domain.Entities.GalleryCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_visible");

                    b.Property<string>("NameJa")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name_ja");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name_vi");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uq_gallery_categories_slug");

                    b.ToTable("gallery_categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_gallery_categories_display_order", "display_order >= 0");
                        });
                });

            modelBuilder.Entity("HBP.Domain.Entities.GalleryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CaptionJa")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("caption_ja");

                    b.Property<string>("CaptionVi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("caption_vi");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<Guid>("GalleryCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("gallery_category_id");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_visible");

                    b.Property<Guid>("MediaFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_file_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("MediaFileId");

                    b.HasIndex("GalleryCategoryId", "IsVisible", "DisplayOrder")
                        .HasDatabaseName("idx_gallery_items_category_visible_order");

                    b.ToTable("gallery_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_gallery_items_display_order", "display_order >= 0");
                        });
                });

            modelBuilder.Entity("HBP.Domain.Entities.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AltTextJa")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("alt_text_ja");

                    b.Property<string>("AltTextVi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("alt_text_vi");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("PublicUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("public_url");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_path");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stored_file_name");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.ToTable("media_files", null, t =>
                        {
                            t.HasCheckConstraint("ck_media_files_size_bytes", "size_bytes >= 0");
                        });
                });

            modelBuilder.Entity("HBP.Domain.Entities.RoomType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("AreaSquareMeters")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("area_square_meters");

                    b.Property<string>("BedDescriptionJa")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bed_description_ja");

                    b.Property<string>("BedDescriptionVi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bed_description_vi");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DescriptionJa")
                        .HasColumnType("text")
                        .HasColumnName("description_ja");

                    b.Property<string>("DescriptionVi")
                        .HasColumnType("text")
                        .HasColumnName("description_vi");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<Guid?>("FeaturedMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("featured_media_id");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_visible");

                    b.Property<string>("NameJa")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_ja");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_vi");

                    b.Property<PriceDisplayMode>("PriceDisplayMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("price_display_mode")
                        .HasDefaultValue(PriceDisplayMode.CONTACT)
                        .HasColumnName("price_display_mode");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_usd");

                    b.Property<decimal?>("PriceVnd")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("price_vnd");

                    b.Property<string>("SeoDescriptionJa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("seo_description_ja");

                    b.Property<string>("SeoDescriptionVi")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("seo_description_vi");

                    b.Property<string>("SeoTitleJa")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("seo_title_ja");

                    b.Property<string>("SeoTitleVi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("seo_title_vi");

                    b.Property<string>("ShortDescriptionJa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_description_ja");

                    b.Property<string>("ShortDescriptionVi")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_description_vi");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_room_types_code");

                    b.HasIndex("FeaturedMediaId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uq_room_types_slug");

                    b.HasIndex("IsVisible", "DisplayOrder")
                        .HasDatabaseName("idx_room_types_visible_order");

                    b.ToTable("room_types", null, t =>
                        {
                            t.HasCheckConstraint("ck_room_types_capacity", "capacity >= 1");

                            t.HasCheckConstraint("ck_room_types_display_order", "display_order >= 0");

                            t.HasCheckConstraint("ck_room_types_price_usd", "price_usd IS NULL OR price_usd >= 0");

                            t.HasCheckConstraint("ck_room_types_price_vnd", "price_vnd IS NULL OR price_vnd >= 0");
                        });
                });

            modelBuilder.Entity("HBP.Domain.Entities.RoomTypeAmenity", b =>
                {
                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.Property<Guid>("AmenityId")
                        .HasColumnType("uuid")
                        .HasColumnName("amenity_id");

                    b.Property<int?>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.HasKey("RoomTypeId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("room_type_amenities", (string)null);
                });

            modelBuilder.Entity("HBP.Domain.Entities.RoomTypeMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<Guid>("MediaFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_file_id");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.HasKey("Id");

                    b.HasIndex("MediaFileId");

                    b.HasIndex("RoomTypeId", "MediaFileId")
                        .IsUnique()
                        .HasDatabaseName("uq_room_type_media");

                    b.ToTable("room_type_media", null, t =>
                        {
                            t.HasCheckConstraint("ck_room_type_media_display_order", "display_order >= 0");
                        });
                });

            modelBuilder.Entity("HBP.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DescriptionJa")
                        .HasColumnType("text")
                        .HasColumnName("description_ja");

                    b.Property<string>("DescriptionVi")
                        .HasColumnType("text")
                        .HasColumnName("description_vi");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<Guid?>("FeaturedMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("featured_media_id");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_visible");

                    b.Property<string>("NameJa")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_ja");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_vi");

                    b.Property<string>("PriceNoteJa")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("price_note_ja");

                    b.Property<string>("PriceNoteVi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("price_note_vi");

                    b.Property<string>("ShortDescriptionJa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_description_ja");

                    b.Property<string>("ShortDescriptionVi")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_description_vi");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("FeaturedMediaId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uq_services_slug");

                    b.HasIndex("IsVisible", "DisplayOrder")
                        .HasDatabaseName("idx_services_visible_order");

                    b.ToTable("services", null, t =>
                        {
                            t.HasCheckConstraint("ck_services_display_order", "display_order >= 0");
                        });
                });

            modelBuilder.Entity("HBP.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("HBP.Domain.Entities.BookingRequest", b =>
                {
                    b.HasOne("HBP.Domain.Entities.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HBP.Domain.Entities.GalleryItem", b =>
                {
                    b.HasOne("HBP.Domain.Entities.GalleryCategory", "GalleryCategory")
                        .WithMany("GalleryItems")
                        .HasForeignKey("GalleryCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HBP.Domain.Entities.MediaFile", "MediaFile")
                        .WithMany()
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GalleryCategory");

                    b.Navigation("MediaFile");
                });

            modelBuilder.Entity("HBP.Domain.Entities.RoomType", b =>
                {
                    b.HasOne("HBP.Domain.Entities.MediaFile", "FeaturedMedia")
                        .WithMany()
                        .HasForeignKey("FeaturedMediaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FeaturedMedia");
                });

            modelBuilder.Entity("HBP.Domain.Entities.RoomTypeAmenity", b =>
                {
                    b.HasOne("HBP.Domain.Entities.Amenity", "Amenity")
                        .WithMany("RoomTypeAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HBP.Domain.Entities.RoomType", "RoomType")
                        .WithMany("RoomTypeAmenities")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HBP.Domain.Entities.RoomTypeMedia", b =>
                {
                    b.HasOne("HBP.Domain.Entities.MediaFile", "MediaFile")
                        .WithMany()
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HBP.Domain.Entities.RoomType", "RoomType")
                        .WithMany("RoomTypeMedia")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HBP.Domain.Entities.Service", b =>
                {
                    b.HasOne("HBP.Domain.Entities.MediaFile", "FeaturedMedia")
                        .WithMany()
                        .HasForeignKey("FeaturedMediaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FeaturedMedia");
                });

            modelBuilder.Entity("HBP.Domain.Entities.Amenity", b =>
                {
                    b.Navigation("RoomTypeAmenities");
                });

            modelBuilder.Entity("HBP.Domain.Entities.GalleryCategory", b =>
                {
                    b.Navigation("GalleryItems");
                });

            modelBuilder.Entity("HBP.Domain.Entities.RoomType", b =>
                {
                    b.Navigation("RoomTypeAmenities");

                    b.Navigation("RoomTypeMedia");
                });
#pragma warning restore 612, 618
        }
    }
}
